import 'package:floor/floor.dart';

@entity
class MET {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  //The met-min value of the exercise
  final double met;

  //When the exercise occured
  final DateTime dateTime;
  
  //exercise id (foreigner key)
  final int? exID;

  //Default constructor
  MET(this.id, this.met, this.dateTime, this.exID);
}